# Generated by Django 4.2.3 on 2023-07-24 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edirektoriapjiiapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('tanggal', models.DateField()),
                ('deskripsi', models.CharField(max_length=500)),
                ('detail', models.CharField(max_length=250)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edirektoriapjiiapps.masterkategori')),
            ],
        ),
        migrations.DeleteModel(
            name='MasterData',
        ),
    ]
